### ISSUE TITLE
Mover para o repositório do Agenda Beleza...

### ISSUE THREAD

**Issue by giovannibonetti** [tiagopog/smart_rspec#1]
...para dar crédito a todos da equipe que participaram do seu desenvolvimento

**Comment by tiagopog** [comment]
A gem foi criada do zero, a partir de uma lib que estava fazendo para o Wordmaster (projeto pessoal). Tomei por base apenas o nome de alguns métodos que utilizamos no Agenda Beleza (belongs_to, has_attributes, has_many, has_one), tirando isso, a base de código é totalmente distinta.
